twitter:
  consumer_key: 'SjLlVEEPBDCvSkL9IzVrsUZmW'
  consumer_secret: 'j14UeT1A32yuULZfXgtB4UsZ4xjjYTXDP5oOK6GlnkapWasndI'

default_token:
  token: '1323793131347664899-6PWrQooyWkyG6vXQCBFlDeH71TMgP3'
  secret: 'ZoxVGvYjrRIQQQdeQH3yWGfSK8Ui3LuNRVT6wUuk2TYWu'